# Generated by Django 4.0.10 on 2023-03-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_content',
            name='bild',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
