# Generated by Django 4.0.10 on 2023-04-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_image',
            field=models.ImageField(default='', upload_to='yoolink/'),
        ),
    ]
