# Generated by Django 4.0.10 on 2023-03-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_galerie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galerie',
        ),
    ]
