# Generated by Django 4.0.10 on 2023-03-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_galerie'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('uploaddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
