# Generated by Django 4.0.10 on 2023-03-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_fileentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fileentry',
        ),
    ]
