# Generated by Django 4.0.10 on 2023-03-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_fileentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileentry',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
    ]
