# Generated by Django 4.0.10 on 2023-03-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_alter_fileentry_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=70, null=True)),
                ('answer', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
