# Generated by Django 4.0.10 on 2023-04-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileentry',
            name='file',
            field=models.FileField(upload_to='upload'),
        ),
    ]
