# Generated by Django 4.0.10 on 2023-04-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_alter_fileentry_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileentry',
            name='file',
            field=models.ImageField(upload_to='yoolink/'),
        ),
    ]
